### ISSUE TITLE
Official js lib

### ISSUE THREAD

**Issue by angelorc** [okex/exchain#296]
Is there any official js lib?

**Comment by angelorc** [comment]
Also it could be useful to add a swagger testing system like this https://cosmos.network/rpc/

**Comment by zccst** [comment]
We currently do not have the same system as cosmos, but you can refer to [OKChain HTTP](https://documenter.getpostman.com/view/1112175/SzS5u6bE?version=latest#03709c4f-d620-4fef-a36a-f9cb97e909b8)
